# Generated by Django 3.1.3 on 2020-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0004_pedido_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='imagem',
            field=models.ImageField(blank=True, default='indice.jpeg', null=True, upload_to='itens_da_cantina'),
        ),
    ]
