# Generated by Django 3.1.3 on 2020-12-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0005_auto_20201220_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(default='indice.jpeg', upload_to='imagens_aluno'),
        ),
        migrations.AddField(
            model_name='escola',
            name='imagem',
            field=models.ImageField(default='indice.jpeg', upload_to='imagens_escola'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='imagem',
            field=models.ImageField(default='indice.jpeg', upload_to='itens_da_cantina'),
        ),
    ]
