# Generated by Django 3.1.3 on 2020-12-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0007_aluno_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodo',
        ),
    ]
